version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    assignees:
      - ffflorian
    versioning-strategy: increase
    ignore:
      - dependency-name: '@types/node'
        versions:
          - '> 24.x'
      - dependency-name: '@types/eslint'
        versions:
          - '> 8.x'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    assignees:
      - ffflorian
