language: node_js
node_js:
  - "10"

cache:
  yarn: true
  directories:
    - "node_modules"

notifications:
  email:
    on_failure:
      change
    on_success:
      never

before_install:
  - curl https://yarnpkg.com/install.sh -sSfL | bash -s --
  - export PATH="${HOME}/.yarn/bin:${PATH}"

script:
  - yarn
  - yarn dist
